// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCitbPTV_4vQnvrbx6Irg4tDz28_2x4TnA',
    appId: '1:810182055174:web:72f1f63d38d7b26a937a87',
    messagingSenderId: '810182055174',
    projectId: 'my-comm-94b58',
    authDomain: 'my-comm-94b58.firebaseapp.com',
    storageBucket: 'my-comm-94b58.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA242KMUnUIlmdmGY-d0KtBnxXMBF3XmyQ',
    appId: '1:810182055174:android:af342c884b783496937a87',
    messagingSenderId: '810182055174',
    projectId: 'my-comm-94b58',
    storageBucket: 'my-comm-94b58.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_--mt0-M1v5rTbRQvruANzoKCq1prbbA',
    appId: '1:810182055174:ios:968379b27ed7307a937a87',
    messagingSenderId: '810182055174',
    projectId: 'my-comm-94b58',
    storageBucket: 'my-comm-94b58.appspot.com',
    iosClientId: '810182055174-734mmpto0d76i72j7elcoavme6tqe8vr.apps.googleusercontent.com',
    iosBundleId: 'com.example.myCom',
  );
}
